### PR TITLE
Add min- and maxLength options for text input

### LINKED ISSUE #62: Option to Controls Maximum & Minimum character in a text field
A new option to control maximum and minimum characters that can be inserted in the text field.

### PR DESCRIPTION
**Pull request by simonhammes**
fixes #62 

... could also be solved with a regex pattern but this option is more beginner-friendly.
Generating the regEx ourselves would probably collide too easily with a custom user-entered regex pattern

Also: minified the dist/ files, again

### CODE REVIEW

**Comment by simonhammes** [comment]
Problem: The minLength attribute does not prevent the user from submitting the form (or the field, rather) with the preset value (e.g. without modifying it). This is in the design of the minLength attribute. I thought about automatically setting the required attribute when the minLength attribute is set?

**Comment by ZafarKamal123** [comment]
Thanks for doing it this far! I will take a look at this later 😉.

**Comment by ZafarKamal123** [comment]
> Problem: The minLength attribute does not prevent the user from submitting the form (or the field, rather) with the preset value (e.g. without modifying it). This is in the design of the minLength attribute. I thought about automatically setting the required attribute when the minLength attribute is set?

I think it works perfect as it is right now, The condition of minimum and maximum characters does not apply if the field is empty and the field is not required. But it does apply when there is some value on the field.

**Comment by simonhammes** [comment]
> I think it works perfect as it is right now, The condition of minimum and maximum characters does not apply if the field is empty and the field is not required. But it does apply when there is some value on the field.

Okay.
It's only pseudo-validation anyway, right? The user could always modify the HTML to enter anything else (or use a browser without html pattern support?)

**Comment by ZafarKamal123** [comment]
Yes, t's only pseudo-validation. But most of the validation is double-checked in the php also before submitting the form. 😉

**Comment by simonhammes** [comment]
Ah right. I haven't looked at the PHP code a whole lot

**Pull request merged**
